### ISSUE TITLE
Culture is not supported for Countries()() on kubernetes

### ISSUE THREAD

**Issue by trandus** [aliostad/RandomGen#21]
Hi!

I get errors when I call the Gen.Random.Countries()() method in the Swarm container.

```
$ locale
LANG=C.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

```
Error Message:
System.Globalization.CultureNotFoundException : Culture is not supported. (Parameter 'culture') 4096 (0x1000) is an invalid culture identifier.
Stack Trace:
at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
at System.Globalization.RegionInfo..ctor(Int32 culture)
at RandomGen.RandomLink.<>c.<Countries>b__22_0(CultureInfo culture)
at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
at System.Linq.Enumerable.DistinctIterator`1.ToList()
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at RandomGen.RandomLink.Items[T](IEnumerable`1 items, IEnumerable`1 weights)
at RandomGen.RandomLink.Countries()
```

**Comment by jkonecki** [comment]
Hello @trandus, the issue should be fixed in version 1.1.6. Please reopen this issue if the problem persists.
